### PR TITLE
Cleanup interfaces named starting with 'I'

### PR DESCRIPTION
**Pull request by CraftCoderr**
- [x] breaking changes
- [ ] no breaking changes

### changes made to the repository

CloudNet have a relatively large code base and many interfaces named in C# style, which not the best practice for Java. This PR replaces interfaces named starting with `I`, with same named interfaces without `I`. I tried to make as less as possible breaking changes. 

### related issues/discussions
  
#25

### CODE REVIEW

**Comment by CraftCoderr** [comment]
Another way is to use common style for naming. Well, it will be Java project with interfaces named in C#-style. It not good, not bad, it as is. But it better, than different styles within one big project.

**Comment by realPanamo** [comment]
What exactly is breaking here? I can't accept breaking changes with class namings, sorry

**Comment by realPanamo** [comment]
I'm not sure about this, reviewing this will take time and I might have to change some things.
Much afford with no benefits at all.

**Comment by realPanamo** [comment]
I just checked - there are still a lot of classes left that are called with 'I' at the beginning

**Comment by McRuben** [comment]
Some classes are completely removed instead of deprecating them

**Comment by CraftCoderr** [comment]
> I just checked - there are still a lot of classes left that are called with 'I' at the beginning

Yes, work in progress, but i need to know if there some chances to merge, when work would be completed.



> Some classes are completely removed instead of deprecating them

In some cases interfaces duplication is useless, as in factory classes, which should return instances of new interfaces, but may have old interfaces in current implementation.

**Comment by realPanamo** [comment]
Closing due to inactivity.

**Pull request closed without merging**
