### PR TITLE
Fixed Spelling Mistake

### PR DESCRIPTION
**Pull request by LeNinjaHD**
This pull request includes:

- [ ] breaking changes
- [ x ] no breaking changes

### Changes made to the repository:
Fixed Spelling Mistake

### Documentation of test results:
Does not need to be tested

### CODE REVIEW

**Comment by Sarsum** [comment]
Hello, please be aware that spelling mistakes in the german.properties have to be changed at https://cloudnetservice.crowdin.com/cloudnet/de

**Comment by LeNinjaHD** [comment]
Okay

**Comment by LeNinjaHD** [comment]
> Hello, please be aware that spelling mistakes in the german.properties have to be changed at https://cloudnetservice.crowdin.com/cloudnet/de

This is a spelling mistake in a comment tho

**Comment by derklaro** [comment]
We are no longer accepting pull requests targeting v3.

**Pull request closed without merging**
