### PR TITLE
Prevent heap space errors when coping a template from one storage to another

### PR DESCRIPTION
**Pull request by derklaro**
- [ ] breaking changes
- [X] no breaking changes

### changes made to the repository
Prevents heap space overload by coping templates with java streams

### CODE REVIEW

**Comment by derklaro** [comment]
I wasn't able to test the template storages ftp/sftp and the queued ftp template storage. Can somebody take a look for me?

**Comment by derrop** [comment]
The SFTP storage almost works. The SFTP server is on the right side and the local storage on the left side. I copied it using the following command: "t copy ftp:Test/test local:Test/test"
image

**Comment by juliarn** [comment]
FTP seems to work completely :peepoHappy:

**Comment by derrop** [comment]
Between linux and windows? I think the problem with the SFTP is the same as the "clu push lt" between one node on linux and another node on windows.

**Comment by juliarn** [comment]
Yes this could be the problem

**Comment by derklaro** [comment]
@juliarn has you fixed the sftp storage or should i take a look?

**Comment by juliarn** [comment]
I only tested FTP

**Comment by derrop** [comment]
I think it should be easily fixable like I did it here https://github.com/CloudNetService/CloudNet-v3/commit/f4f4fc099f6655e5673f9209c9585e7c52d21822

**Comment by derrop** [comment]
Copying to an SFTP Server works now.

**Comment by derklaro** [comment]
Ah nice

**Comment by derrop** [comment]
So I think we can merge this

**Pull request merged**
