### PR TITLE
Implement chat variable to PermissionGroup

### PR DESCRIPTION
**Pull request by lucabartmann**
This pull request includes:

- [ ] breaking changes
- [x] no breaking changes

### Changes made to the repository:

Add chat variable to permission group to provide an extra layout option for the cloudnet-chat plugin.

### Documentation of test results:

Tested at 3.4 in the [add-chat-variable](https://github.com/germanluca/CloudNet-v3/tree/add-chat-variable) at my fork.

### Related issues/discussions:

  
There are no issues.

### CODE REVIEW

**Comment by TheMeinerLP** [comment]
LGTM

**Comment by 0utplay** [comment]
What is the use case of this new option in the PermissionGroup and why is display now removed partly

**Comment by lucabartmann** [comment]
This chat variable kind of splits the display variable in two parts. The chat variable is just for the chat layout in the cloudnet-chat plugin and the display variable loses this part.

**Comment by derklaro** [comment]
First of all, sorry for the long waiting time you had. I looked at your changes and they look good to me. But, two things:

 * Please target your changes against `unstable/rewrite` as it's the current branch we're working on for the next release.
 * Can you explain every placeholder's functionality? Especially the new ones and which position the display placeholder now takes?

**Comment by lucabartmann** [comment]
Hey,

I will work on a better and larger explanation within the next days. Thanks for reviewing anyways :)

**Comment by derklaro** [comment]
Closing due to inactivity, feel free to open a new pull request in the future! :)

**Pull request closed without merging**
