### PR TITLE
Chat color config change

### LINKED ISSUE #926: CloudNet-Chat ignores group color
### Stacktrace

_No response_

### Actions to reproduce

Version: CloudNet Blizzard 4.0.0-RC4 ab12241
Using both CloudNet-Chat and CloudNet-SimpleNameTags:
```
/cloud perms group admin set prefix "&x&f&f&0&0&f&fAdmin &4| "
/cloud perms group admin set color &7
```
Join the admin group.

Player list looks like this:
image

While chat looks like this, ignoring the color:
image

### CloudNet version

CloudNet Blizzard 4.0.0-RC4 ab12241

### Other

_No response_

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

### PR DESCRIPTION
**Pull request by Remynfv**
### Motivation

See issue #926 . Default tab list formatting with SimpleNameTags doesn't match the default CloudNet-Chat formatting.

### Modification

Changed the config.yml and config.properties to add color.

### Result

Chat is now formatting the same as the player list by default.

##### Other context

Fixes #926 

My first pull request to CloudNet! Hopefully I did this correctly.

### CODE REVIEW

**Comment by 0utplay** [comment]
I am not sure if we should continue using the display as default here. We might consider switching to %prefix%%color%%name%

**Comment by Remynfv** [comment]
%prefix% sounds like it would make more sense, but... what does %display% actually do?

> ``# %display%  - the display of the highest permission group of the player``

Maybe this could be more descriptive?

Also while we're at it, wouldn't it make sense to also use %suffix% at the end?

**Comment by 0utplay** [comment]
We could use %suffix% too, yeah. The display is set as the players display name (that does not appear in the TabList, but when using Player#getDisplayName()).

**Comment by Remynfv** [comment]
setDisplayName is used by a lot of plugins to do nicknames and stuff. I feel like it could cause confusion if that didn't work out of the box. To me at least, _not_ using display names seems like the non-default behavior.

**Comment by Remynfv** [comment]
I think it makes sense to keep %display%, especially for parity with SimpleNameTags. Simplenametags' does specifically mention display names as well.
>  Adds prefix, suffix and **display name** support to all server platforms

In these commits I also moved %display% to be next to %name%, and rephrased their descriptions to be a bit clearer.

**Review by 0utplay — CHANGES_REQUESTED** [review]
Hey, I would ask you to rebase your PR due to recent changes to the sponge impl.

Furtheremore please revert the comment change about the %display% option as it is indeed the display of the group. You can add %display_name% to the available placeholders list, which is the display name of the player.

Lastly, change the default formats in the Nukkit & Sponge code.

**Comment by 0utplay** [comment]
Closed due to inactivity

**Pull request closed without merging**
