### PR TITLE
Better player manager

### PR DESCRIPTION
**Pull request by derrop**
This pull request includes:

- [ ] breaking changes
- [x] no breaking changes

### Changes made to the repository:

Add new methods to the IPlayerManager to get the online players of a task and a group.

### Related issues/discussions:

#255

### CODE REVIEW

**Comment by derklaro** [comment]
There are breaking changes!

**Comment by byRoadrunner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
           

Complexity increasing per file
==============================
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/NodePlayerProvider.java  1
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerProvider.java  1
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/PlayerManagerListener.java  8
         

Complexity decreasing per file
==============================
+ cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerManager.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet-v3/pullRequest?prid=5794530&bid=18966574)

**Comment by juliarn** [comment]
> There are breaking changes!

No, methods just got deprecated

**Comment by derklaro** [comment]
> No, methods just got deprecated
No :)

**Comment by derrop** [comment]
NodePlayerManager#loginPlayer doesn't matter as a breaking change, and it still works if you call the method with a lambda

**Comment by derklaro** [comment]
No comment here xDDDD

**Comment by byRoadrunner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Complexity increasing per file
==============================
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/NodePlayerProvider.java  1
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/PlayerManagerListener.java  11
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerProvider.java  1
         

Complexity decreasing per file
==============================
+ cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerManager.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet-v3/pullRequest?prid=5794530&bid=18966574)

**Comment by byRoadrunner** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 16
           

Complexity increasing per file
==============================
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerProvider.java  1
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/NodePlayerProvider.java  1
- cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/node/listener/PlayerManagerListener.java  11
         

Complexity decreasing per file
==============================
+ cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/BridgePlayerManager.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CloudNetService/CloudNet-v3/pullRequest?prid=5794530&bid=18966574)

**Pull request merged**
