### PR TITLE
Fix NPE when checking velocity console permissions

### PR DESCRIPTION
**Pull request by WebbiiiCC**
This pull request includes:

- [ ] breaking changes
- [X] no breaking changes

### Changes made to the repository:
Return a permission function even when the PermissionSubject is not a player to prevent errors when executing some commands from the console in Velocity

### CODE REVIEW

**Comment by derklaro** [comment]
The provider is only set for players in the setup event...

**Comment by WebbiiiCC** [comment]
There is no check anywhere checking if the PermissionSubject really is a player. PermissionsSetupEvent is also called once for the velocity console so it has to be checked. Either we return a valid PermissionFunction or we add a check to the Event Listener

**Comment by juliarn** [comment]
Its checked in the event, so should be fine
image

**Comment by WebbiiiCC** [comment]
Doesn't show that to me...
https://github.com/CloudNetService/CloudNet-v3/blob/master/cloudnet-modules/cloudnet-cloudperms/src/main/java/de/dytanic/cloudnet/ext/cloudperms/velocity/listener/VelocityCloudNetCloudPermissionsPlayerListener.java#L34

**Comment by juliarn** [comment]
This is on the master branch, we fixed that on development

**Comment by WebbiiiCC** [comment]
Oh i see. Then sorry, my mistake.

**Comment by juliarn** [comment]
No problem, thank your for the report anyway

**Pull request closed without merging**
