### PR TITLE
Replace & to § in the VelocitySyncProxyManagement to avoid unformatte…

### PR DESCRIPTION
**Pull request by 0utplay**
…d messages

This pull request includes:

- [ ] breaking changes
- [x] no breaking changes

### Changes made to the repository:

Replace the color code char in the message

### Documentation of test results:

No tests done.

### Related issues/discussions:

https://discord.com/channels/325362837184577536/536595116630999070/789148275693453353

### CODE REVIEW

**Review by derklaro — CHANGES_REQUESTED** [review]
Consider using `LegacyComponentSerializer.legacyAmpersand().deserialize(message);`

**Comment by einrobin** [comment]
> Consider using `LegacyComponentSerializer.legacyAmpersand().deserialize(message);`

It should support both, this one would only support `&`.

**Comment by derklaro** [comment]
> > Consider using `LegacyComponentSerializer.legacyAmpersand().deserialize(message);`
> 
> It should support both, this one would only support `&`.

There is no way which supports both

**Comment by einrobin** [comment]
> > > Consider using `LegacyComponentSerializer.legacyAmpersand().deserialize(message);`
> > 
> > 
> > It should support both, this one would only support `&`.
> 
> There is no way which supports both

There is, just replace & with § like it is already done

**Comment by derklaro** [comment]
> > > > Consider using `LegacyComponentSerializer.legacyAmpersand().deserialize(message);`
> > > 
> > > 
> > > It should support both, this one would only support `&`.
> > 
> > 
> > There is no way which supports both
> 
> There is, just replace & with § like it is already done

That may break the message displayed

**Pull request closed without merging**
