### PR TITLE
bump gradle to 7.4.2

### PR DESCRIPTION
**Pull request by kxmpxtxnt**
just gradle version change

### CODE REVIEW

**Comment by 0utplay** [comment]
I don't think we have to do that update. We are not updating other dependencies as this branch won't be updated in future

**Comment by kxmpxtxnt** [comment]
It's okay, sorry

**Comment by kxmpxtxnt** [comment]
It's okay, sorry

**Comment by ixn075** [comment]
Did anyone forgot to close it? xD

**Comment by kxmpxtxnt** [comment]
xD

**Pull request closed without merging**
