### PR TITLE
Create french.properties

### PR DESCRIPTION
**Pull request by ArnaudLier**
This pull request includes:

- [ ] breaking changes
- [x] no breaking changes

### Changes made to the repository:

Added the French language

### CODE REVIEW

**Comment by juliarn** [comment]
Hey, thank you for your contribution.
We are working on CloudNet on the development branch, but you created this PR based on the master branch.
Development is quite some commits over the master branch and there were additions and modifications to the language files too.
Could you please check if the french language file is up to date with the messages in the development branch?

**Comment by ArnaudLier** [comment]
✅ It's up-to-date.

**Comment by juliarn** [comment]
If you compare the master and development branches here: https://github.com/CloudNetService/CloudNet-v3/compare/master...development and go to the lang/english.properties, you'll see that there are a couple more messages in development than in master, you should add those messages too.

**Comment by ArnaudLier** [comment]
✅ Here you go, it should be good now.

**Comment by juliarn** [comment]
Looks good, I'll format and then merge this, thank you very much!

**Review by juliarn — APPROVED** [review]

**Comment by ArnaudLier** [comment]
In French, there is spaces in front of punctuation marks.

**Comment by juliarn** [comment]
Does everyone in France do this? I had french lessons in school and never heard of it. xD I personally think that it looks better without spaces, but I can change it again.

**Comment by ArnaudLier** [comment]
Yes, not having spaces before punctuation marks in French is even considered as a mistake: https://www.iwillteachyoualanguage.com/learn/french/french-tips/french-punctuation

**Pull request merged**
