### PR TITLE
New command

### PR DESCRIPTION
**Pull request by McRuben**
- [ ] breaking changes
- [x] no breaking changes

### changes made to the repository
Added copy command to easily copy services to their template

### CODE REVIEW

**Comment by realPanamo** [comment]
Please remove the ``created by ...`` in the comment, and let IntelliJ reformat everything, so it fits to the current style

**Comment by realPanamo** [comment]
Please also don't make the whole template one argument, do it similar to the other commands, first argument the storage, second the prefix, last the name.

**Comment by McRuben** [comment]
It is similar to other commands, just take a look at the create command

**Comment by realPanamo** [comment]
Ah, I didn't see that the template is an optional argument

**Pull request merged**
