### PR TITLE
Add Jenkinsfile for easy CI

### PR DESCRIPTION
**Pull request by GiantTreeLP**
Doesn't really need a comment

### CODE REVIEW

**Comment by realPanamo** [comment]
No, add a comment or I won't merge :kappaLUL:

**Comment by GiantTreeLP** [comment]
Well, I think I need to comment anyways.

The gradlew file needs to be executable and Jenkins (ci.cloudnetservice.eu) can't install Java 8 on its own.

**Comment by 4zuree** [comment]
What's up with this pull request?

**Comment by GiantTreeLP** [comment]
@byRoadrunner can you rebuild this commit?
It's the shit test that relies on way to quick responses.

**Comment by GiantTreeLP** [comment]
@4zuree i don't know exactly which files are needed and @byRoadrunner wanted to make the changes, but I just selected all build artifacts for now.
I just need confirmation that this change is enough, then this PR can be merged.

**Pull request merged**
