### PR TITLE
Update V1HttpHandlerServices.java

### PR DESCRIPTION
**Pull request by chaosfreak93**
This pull request includes:

- [ ] breaking changes
- [x] no breaking changes

### Changes made to the repository:
Added the ability to restart a service from the Rest API

### CODE REVIEW

**Comment by derklaro** [comment]
Please do not create pull requests from/to master.

**Comment by chaosfreak93** [comment]
Which git branch else?

**Comment by derklaro** [comment]
Use development for pull requsts please.

**Comment by chaosfreak93** [comment]
So should open a new pull request?

**Comment by derklaro** [comment]
You can use this one and resolve all merge conflicts, or create a new one from and to development.

**Pull request closed without merging**
